name: test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Python test with 10 numbers
      run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
    - name: Run Diff test with 10 numbers
      run: diff test_data/test1_expected.txt test_data/test1_output.txt
      
    - name: Run Python test with 1 numbers
      run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
    - name: Run Diff test with 1 numbers
      run: diff test_data/test2_expected.txt test_data/test2_output.txt
      
    - name: Run Python test with empty number
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
    - name: Run Diff test with empty number
      run: diff test_data/test3_expected.txt test_data/test3_output.txt
